### ISSUE TITLE
CloudFormation stack creation fails at ECS auto scaling

### ISSUE THREAD

**Issue by electron-volt** [aws-samples/cicd-for-ecs-workshop-code#2]
I'm trying to complete the CI/CD Workshop for Amazon ECS (https://catalog.us-east-1.prod.workshops.aws/v2/workshops/869f7eee-d3a2-490b-bf9a-ac90a8fb2d36/en-US/). I got the Cloud9 IDE set up correctly and the git repo cloned. 

I'm trying to create the prod and staging environment stacks, but both CloudFormation templates fail at the ECSAutoscaling part with cryptic error "The requested configuration is currently not supported". The CloudFormation template in question is  Cluster-ECS-EC2-2AZ-ALB-1NAT.yaml.

I am in region eu-north-1 (Stockholm). Any ideas what's wrong?

**Comment by electron-volt** [comment]
Nevermind - turns out the eu-north-1 region doesn't have t2.micro (which is the default instance type in the template). Changing the default to t3.micro (which we swedes have) solved it!

**Comment by rizblie** [comment]
Thanks for letting us know. Yes newer regions don't have the older EC2 families. I will add a note in the workshop.
